# Generated by Django 2.2 on 2020-07-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=500, null=True)),
                ('gender', models.BooleanField(default='', null=True)),
                ('birthday', models.DateTimeField(default='', null=True)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('video_type', models.CharField(default='other', max_length=10)),
                ('nationality', models.CharField(default='china', max_length=10)),
                ('from_to', models.CharField(default='customer', max_length=10)),
                ('info', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'video_type', 'nationality', 'from_to')},
            },
        ),
        migrations.CreateModel(
            name='VideoSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('url', models.CharField(max_length=300)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vedeo_subs', to='app.Video')),
            ],
            options={
                'unique_together': {('video', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VideoStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identify', models.CharField(default='', max_length=50)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_stars', to='app.Video')),
            ],
            options={
                'unique_together': {('video', 'name')},
            },
        ),
    ]
