# Generated by Django 2.2 on 2020-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='from_to',
            field=models.CharField(default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='nationality',
            field=models.CharField(default='china', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
