# Generated by Django 2.2 on 2020-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200707_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosub',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
