# Generated by Django 2.2 on 2020-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_videosub_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosub',
            name='role',
        ),
        migrations.AddField(
            model_name='videostar',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
